{% set name = "fastapi-mail" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 22db99be0a842b0535d4cc01712a1677abcbb94fd11cca6bf5e8826139116b00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.1,<4.0
    - pip
    - poetry-core >=1.2.0
  run:
    - python >=3.8.1,<4.0
    - jinja2 >=3.0.1,<4.0.0
    - aiosmtplib >=2.0,<3.0.0
    - blinker >=1.5,<2.0
    - email-validator >=1.1.3,<2.0.0
    - pydantic >=1.8.2,<2.0.0
    - starlette

test:
  imports:
    - fastapi_mail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sabuhish/fastapi-mail
  summary: Simple lightweight mail library for FastApi
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
