context:
  version: 1.4.2
  python_min: "3.9"

package:
  name: fastapi-mail
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastapi-mail/fastapi_mail-${{ version }}.tar.gz
  sha256: 04bde1005c624f42dfc0a9c1e313fcc544499fdd6b3531e606c500d80ac2ffcb

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - jinja2 >=3.0.0,<4.0.0
    - blinker >=1.5.0,<2.0.0
    - starlette >=0.24,<1.0
    - aiosmtplib >=3.0.2,<4.0.0
    - pydantic >=2.10.1,<3.0.0
    - email-validator >=2.2.0,<3.0.0
    - pydantic-settings >=2.6.1,<3.0.0
  run_constraints:
    - httpx >=0.23.0,<0.24.0
    - redis-py >=4.3.0,<5.0.0

tests:
  - python:
      imports:
        - fastapi_mail
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Simple lightweight mail library for FastApi
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/sabuhish/fastapi-mail

extra:
  recipe-maintainers:
    - synapticarbors
